services:
  db:
    image: postgres:13
    environment:
      DB_HOST: db
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U SuperDev0l0per -d nexus_scholar"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./nexus-scholar-key.json:/app/nexus-scholar-key.json:ro
    depends_on:
      db:
        condition: service_healthy
    platform: linux/amd64
    command: go run cmd/api/main.go

volumes:
  postgres_data: